name: Reusable Playwright Tests & Allure Report

on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
        default: 'All'
        description: 'Specify which component tests to run (All, FrontEnd, BackEnd)'
    # secrets:
    #   GITHUB_TOKEN: # GITHUB_TOKEN is automatically provided by GitHub Actions unless you explicitly override it.
    #     required: true
    #     description: 'GitHub token for deploying to GitHub Pages and setting commit status'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      statuses: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ github.event.inputs.component == 'All' || github.event.inputs.component == '' }}
        run: npx playwright test --reporter=line,allure-playwright
      - name: Run FrontEnd tests
        if: ${{ github.event.inputs.component == 'FrontEnd' }}
        run: npx playwright test --grep @FrontEnd --reporter=line,allure-playwright
      - name: Run BackEnd tests
        if: ${{ github.event.inputs.component == 'BackEnd' }}
        run: npx playwright test --grep @BackEnd --reporter=line,allure-playwright
        # Allure results will be in allure-results/

  generate-report-and-deploy-to-gh-pages:
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      id: download-artifacts
      if: always()
      with:
          name: allure-results
          path: allure-results

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages

    - name: Generate Allure Report
      uses: carlosmanzatto/gen-allure@main
      if: always()
      id: allure-report
      with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
          report_url: https://carlosmanzatto.github.io/playwright-reports/

    - name: Deploy report to Github Pages
      if: always()
      uses: carlosmanzatto/deploy-gh-pages@main
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history

